spring:
  datasource:
    url: ${mysql_url}
    username: ${mysql_username}
    password: ${mysql_password}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    defer-datasource-initialization: true

  #Gmail Configuration
  mail:
    host: smtp.gmail.com
    port: ${mail_port}
    username: ${mail_username}
    password: ${mail_password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  publicData:
    serviceKey: ${public_data_service_key}

  jwt:
    secret: ${jwt_secret}
    issuer: admin
    access_token_expiration_time: 86400000 #1일
    refresh_token_expiration_time: 864000000 #7일
