spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:3306/${MYSQL_DATABASE}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    defer-datasource-initialization: true

  publicData:
    serviceKey: ${PUBLIC_DATA_SERVICE_KEY}

  jwt:
    secret: ${JWT_SECRET}
    issuer: admin
    access_token_expiration_time: 86400000 #1일
    refresh_token_expiration_time: 864000000 #7일
