spring:
  datasource:
    url: ${url}
    username: ${username}
    password: ${password}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    defer-datasource-initialization: true

  #Gmail ??
  mail:
    host: smtp.gmail.com
    port: ${port}
    username: ${username}
    password: ${password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  publicData:
    serviceKey: ${serviceKey}

  jwt:
    secret: ${secret}
    issuer: admin
    access_token_expiration_time: 86400000 #1일
    refresh_token_expiration_time: 864000000 #7일
